### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [anhpnguyen/first-rails-app#1]
I love the Bootstrap integration! The project is mostly looking very good, but there are two stylistic updates I'd like you to make, listed below.
### Getting rid of `.DS_Store` clutter

OS X automatically generates hidden `.DS_Store` files and by default, Git will include them your commits. To get rid of this clutter in our Git repos, you can [check out this link](http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository).
### Indentation in Rails projects

I see a lot of hard-tabs throughout the project, while the standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.
### Bootstrap integration tips (optional)

This final one is optional, since your Bootstrap integration is above-and-beyond, but the more typical way of including Bootstrap in a Rails project is through [the `bootstrap-sass` gem](https://github.com/twbs/bootstrap-sass#a-ruby-on-rails). This will allow you to do fancy things like override Bootstrap variables before it compiles, use Bootstrap mixins and variables in your own SCSS, and very easily configure which parts of Bootstrap you want and which you want to leave out, if you choose to slim down.

**Comment by anhpnguyen** [comment]
Good morning Chris! I have updated the indentations. About the SASS, I
wasn't able to get it right, so I'll just show you in class.

Thanks!

Anh Nguyen

**Comment by chrisvfritz** [comment]
:+1: Much better!
